# source and destination Settings
source:      _source
destination: _site

# keep pages organized
include: ["_pages"]

# User Settings | Edit there as per required

title: Jorg Thuijls | SAP developer
url: "https://jorg.thuijls.net"
baseurl: ""

# This will show up at the top of index page
site_heading: >
    <span class="faded">Jorg</span> Thuijls

email: jorg@thuijls.net
author: Jorg Thuijls
# This description will show up in google search results
# (for index page) etc.
description: >
    Learn more about Jorg Thuijls, SAP and UI5 developer. Check out his resume and blog!

# This will what will show against &copy; in the footer
copyright: Jorg
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: true         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    Welcome! This is the homepage of Jorg Thuijls, SAP ABAP and UI5 developer. My site is 
    still under development, but I was dying to get something going :)

permalink: /blog/:year/:month/:day/:title.html

# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Jorg is a SAP and UI5 developer.

about_footer: true

twitter_username: _jorgt
github_username: jorgt
facebook_id: jorg.thuijls

favicon: true
favicon_location: "/images/favicon.ico"

profile_picture: /images/jorghead1.png
# paginate: 20
# paginate_path: "blog/page/:num"
tracking_id: UA-55534832-3 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/accent.png" # This will show in facebook thumbnails
twitter_image: "images/jorg.jpg" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems: [pygments.rb, jekyll-press]

highlighter: pygments

sass:
    style: compressed
    sass_dir: _sass

jekyll-press:
    exclude: ['feed.xml', 'robots.txt', 'sitemap.xml'] # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
    js_options: {}      # js minifier options
    css_options: {}     # css minifier options
    html_options: {}    # html minifier options

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
